plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@atls/plugin-essentials.js

yarnPath: .yarn/releases/yarn-berry.cjs
packageExtensions:
  'webpack@*':
    dependencies:
      '@types/webpack': '5.28.0'
      '@types/webpack-dev-server': '^3.11.2'
      '@types/html-webpack-plugin': '3.2.6'
      '@types/html-webpack-template': '6.0.6'
      '@types/webpack-env': '1.16.2'
      '@types/webpack-sources': '2.1.1'
