name: Deploy project
on:
  push:
    branches:
      - master
jobs:
  web-diary:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: practice/web-diary/dist
